### ISSUE TITLE
Problem on all the code

### ISSUE THREAD

**Issue by johanvilela** [Miguelflj/Arquitetura_Microprocessador#1]
I found a critical error on your project. 
Delete and redo it!

**Comment by luanteylo** [comment]
We have been working hard to improve this project because of your comment. 

It started has a small microprocessor simulator, but now we already have an Operating System called vilela_OS (yes, it is named after you).

Please check it out.

Because of such good comments like yours, great projects are borne.

Thank you very much for such a huge contribution
